### ISSUE TITLE
Custom label of the "message" field doesn't work

### ISSUE THREAD

**Issue by onOffice-Web** [onOffice-Web-Org/oo-wp-plugin#514]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/512

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** May  2, 2023</sup>
### Current state

When filling out the custom label for the “message” field the value seems to be saved in WP backend, but not displayed in the frontend. See the attached screenshot.

### Desired state

The custom label should be displayed.

![custom-label-wp](https://user-images.githubusercontent.com/88546396/235683728-e48af8b2-c9d4-4a33-a17f-ee572dff9038.jpg)
![custom-label-frontend](https://user-images.githubusercontent.com/88546396/235683735-4de7fb39-16a3-451f-bb24-1637c95ee207.jpg)
</div>

**Comment by dai-eastgate** [comment]
Hi @fredericalpers 
Now I checked and see that.
The "message" label is being fixed HTML code in the "defaultform.php" file in the "templates.dist" directory.
So the only solution we must edit the file "defaultform.php"
![image](https://user-images.githubusercontent.com/106214469/236388988-086b7d85-240f-4f2f-9c8b-2a45348199a3.png)

But this will affect backward compatibility. Because the customer may have copied and edited the template "defaultform.php" in the Template customizations "onoffice-personalized" folder.
Please give me your opinion on this matter.

**Comment by fredericalpers** [comment]
> Hi @fredericalpers Now I checked and see that. The "message" label is being fixed HTML code in the "defaultform.php" file in the "templates.dist" directory. So the only solution we must edit the file "defaultform.php" ![image](https://user-images.githubusercontent.com/106214469/236388988-086b7d85-240f-4f2f-9c8b-2a45348199a3.png)
> 
> But this will affect backward compatibility. Because the customer may have copied and edited the template "defaultform.php" in the Template customizations "onoffice-personalized" folder. Please give me your opinion on this matter?

@dai-eastgate please go ahead and fix it. The basic defaultform in "template.dist" directory should be fixed. Customers with customized templates will have to copy the new code from the defaultform to their templates if necessary.

**Comment by dai-eastgate** [comment]
@fredericalpers  I will fix it.

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed the custom label of the "message" field. Please take a look at the video below and give me your feedback

https://files.fm/u/y9frqfep5

**Comment by fredericalpers** [comment]
> feedback

@dai-eastgate seems good to me! thank you :)
