### ISSUE TITLE
Ownerform - Create address and property

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#541]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/536

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** May 26, 2023</sup>
### Current state

If “Create Address and Property” is disabled in the WordPress backend, the information from the Ownerform will not be sent in the email. Only the data to of the user will be sent.

### Desired state
All information from the form should be sent in the email at all times.
</div>

**Comment by yeneastgate** [comment]
@fredericalpers For this issue, it is quite complicated, so I need time to investigate closely, I will let you know tomorrow. Thanks!

**Comment by yeneastgate** [comment]
@fredericalpers We found solution and will implement it in this cycle. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers 
I added the estate information from the Owner form to the email when I disabled the "Create address and property" checkbox. I would like to confirm the format of the email sent. Please take a look at the sentence in the red box inside the attached image and let me know if it is right or not. Thanks!

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/1b1edfc9-b33d-4a31-9249-943e6429deeb)

**Comment by onOffice-Web** [comment]
> @fredericalpers I added the estate information from the Owner form to the email when I disabled the "Create address and property" checkbox. I would like to confirm the format of the email sent. Please take a look at the sentence in the red box inside the attached image and let me know if it is right or not. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/106214469/244656544-1b1edfc9-b33d-4a31-9249-943e6429deeb.png)

@dai-eastgate 

the content of the mail should be as followed (so its the same as if the checkbox for "create address.." is enabled.
First the Data from the form such as where its from and the input to the fields for the property, then the data for the owner and then the message:

Daten zum abgesendeten Formular
--------------------------------------------------
Herkunft Webseite: /eigentuemerformular/
Formular-Typ: owner
Immobilie: 10 (ImmoNr), 65 (Datensatznr)
Vermarktungsart: Kauf
Objektart: Haus
Wohnfläche: 123,00
PLZ: 52068
Ort: Aachen


Daten zum Benutzer
--------------------------------------------------
Name: Alperswer
Straße: Charlottenburger Allee 5
Plz: 52068
Ort: Aachen
Telefonnummern: 123456
E-Mail: f.alpers@onoffice.de
: 1
AGB akzeptiert: Ja


Nachricht des Benutzers
--------------------------------------------------
Nachricht: Message from the owner

**Comment by dai-eastgate** [comment]
@fredericalpers 
Yes, I will create content in the email format as mentioned above.
However, the following information will not be included in the content of the email. Because these information is only generated when the checkbox for "Create Address and Property" is enabled.

Anfrage zu der Immobilie 162772
Immobilie: 162772 (ImmoNr), 361275 (Datensatznr)

So, this would be the content I could create:

Daten zum abgesendeten Formular
--------------------------------------------------
Herkunft Webseite: /owner-form/
Formular-Typ: owner
Vermarktungsart: Miete
Objektart: Grundstück
Objekttyp: Freizeit
Wohnfläche: 23,00
PLZ: 1234
Ort: ha noi


Daten zum Benutzer
--------------------------------------------------
Vorname: test
Name: test Create Address and Property
E-Mail: daitrinhduc@gmail.com

Nachricht des Benutzers
--------------------------------------------------
Nachricht: Message from the owner

**Comment by fredericalpers** [comment]
@dai-eastgate yes! thank you :)
