### ISSUE TITLE
Sort property lists

### ISSUE THREAD

**Issue by onOffice-Web** [onOffice-Web-Org/oo-wp-plugin#549]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/507

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April 25, 2023</sup>
### Current state

At the moment the created property lists can not be sorted. With a large number of lists, it is difficult to find the correct one.

### Desired state

The ones marked in the screenshot should be sortable, like in the WP page overview. Sorting for "Name of list", "Selected filter", "Template" and "List type".

![sort-property-lists](https://user-images.githubusercontent.com/88546396/234275407-562cf5a9-3aa7-4097-8dad-90c09dcc0067.jpg)
</div>

**Comment by dai-eastgate** [comment]
@fredericalpers Currently, the 4 fields you want to be sorted, must be sorted by the value in the database.
I checked in the code and found that 3 fields: "Name of the list", "Template" and "List type" can be sorted normally because in the database it is stored as a name. But the "Selected filter" field is stored as an id in the database while the plugin has displayed that field as a name. 
Therefore, I can only sort this "Selected filter" field by id. 
Please let me know your opinion about this. Thanks.

**Comment by yeneastgate** [comment]
> > 
> 
> Please go ahead and first implement the 3 fields "Name of the list", "Template" and "List type".
> 
> For the "selected filter" we will have to discuss it internally again. Thank you.
> 
> edit: what is your time estimate on this?

I need 3 days to implement 3 fields "Name of the list", "Template" and "List type".

**Comment by dai-eastgate** [comment]
> > 
> 
> Please go ahead and first implement the 3 fields "Name of the list", "Template" and "List type".
> 
> For the "selected filter" we will have to discuss it internally again. Thank you.
> 
> edit: what is your time estimate on this?

I need 3 days to implement the sort of 3 fields "Name of the list", "Template" and "List type".

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented the sort feature for these 3 fields:  "Name of the list", "Template" and "List type". Please take a look at my video and let me know your opinion. Thanks! 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/158c7587-5e49-4642-916b-df7fa386f577
