### ISSUE TITLE
Load reCAPTCHA on focus only

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#556]
### Current state

When activated, reCAPTCHA significantly reduces the pagespeed.

### Desired state
To achieve a better pagespeed when reCAPTCHA is not needed or in use the scripts should only be loaded when the user focuses on an input field.

**Comment by fredericalpers** [comment]
Locked until working on v4.16

**Comment by dai-eastgate** [comment]
Hi @fredericalpers, I would like to confirm some points:
1. "When reCAPTCHA is not needed" means: When the user has Google reCAPTCHA's "site key" and "secret key" installed but the "Requires Captcha" checkbox is not enabled in the Backend of the Forms  => We don't load the reCAPTCHA javascript file right?

2. "When reCAPTCHA is in use the scripts should only be loaded when the user focuses on an input field." means:
- The word "focus on" that you mention is the Onfocus property of HTML DOM Events, right?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/d5547a71-0457-4673-a69f-37383ead67fc)

=> When the user clicks (focus) on any input of the form, we will start loading the javascript file of reCAPTCHA right?

**Comment by fredericalpers** [comment]
> "When reCAPTCHA is not needed" means: When the user has Google reCAPTCHA's "site key" and "secret key" installed but the "Requires Captcha" checkbox is not enabled in the Backend of the Forms => We don't load the reCAPTCHA javascript file right?

Yes, that would be ideal for this case.


> "When reCAPTCHA is in use the scripts should only be loaded when the user focuses on an input field." means:
> ![255137306-d5547a71-0457-4673-a69f-37383ead67fc](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/b9e6cb1f-ba90-4fdf-8ad5-826cb225030c)
> => When the user clicks (focus) on any input of the form, we will start loading the javascript file of reCAPTCHA right?

Yes, thats the idea. We will have to see if the google score will be affected and more normal visitors will be recognized as spam. But for now we want to imporve the performance with this.

**Comment by dai-eastgate** [comment]
@fredericalpers I need 6 days to implement and test because we have changed a lot of files. Thanks!

**Comment by dai-eastgate** [comment]
Hi @fredericalpers, I have completed implementing and testing the cases we discussed above. Please watch the attached video and let me know your opinion. 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/493fe078-6a3a-4537-8fa9-d4ae013ed1e2

Concerning the question about the potential impact of Google score and spam recognition, I also researched and had the following comments:
1. By loading reCAPTCHA only when the user interacts: Google's score will increase on plugin pages that don't need to load recaptcha (because it doesn't need time to load the recaptcha file). For example: The Estate List
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/c07cfcef-4f4b-4e99-bd65-e05a3d28e49e)

And on pages that need to load recaptcha, Google score will not be affected or increase a bit because we are loading asynchronously (limiting the possibility of HTML being blocked while waiting to load the js reCAPTCHA file). 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/4894ace2-3acc-4e4a-967f-469b790225f3)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8000e171-e8f0-4215-b9a1-100351204b2e)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/c165fa9a-a427-4028-96df-d29377544b31)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/02668301-7c12-4b41-8a7b-787d62eab477)

2. Normal visitors will be recognized as spam:
The evaluation of a user as a spam bot or a real user when accessing the website is due to Google captcha's algorithm
=> The fact that we only load the js file when the focus does not interfere or have anything to do with the Google captcha algorithm => Normal visitors will not be considered spam

**Comment by fredericalpers** [comment]
Looks good to me. Can't wait to test and release this! thank you :)
