### ISSUE TITLE
Leaflet.js Update

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#703]
Currently the plugin is still using the outdated version 1.3.4 from 08/2018. There have been quite a few updates since. The newest version from 05/2023 is version 1.9.4.

- https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md

- [x] The leaflet.js should be updated to the newest version.
- [ ] Fix the bug mentioned in comment https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/703#issuecomment-1907305962 after https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/695

**Comment by dai-eastgate** [comment]
@fredericalpers I currently have no effort to investigate this issue in this cycle. Therefore, I will continue to investigate it in the next cycle. Thanks!

**Comment by yeneastgate** [comment]
@fredericalpers I have updated the Leaflet library to version 1.9.4, here is video evidence.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/1a1a1581-92b5-4355-9104-58e0ef325399

Note: While testing the "leaflet" library, I found an error. In the case of multiple property lists on a single page, the map is not working properly (only the map of the first Estate List can be read), the cause of the bug is that the ID of each Estate List is the same.
If you want to fix this bug, please create a new issue. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate I think this problem should be fixed with Issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/695 where we implement improvements to the pagination of property lists. I will move this to v4.21 :) thank you :)

**Comment by fredericalpers** [comment]
Come back to fixing this after reviewing and releasing https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/695
