### ISSUE TITLE
Script Loading issue for onoffice-captchacontrol.min.js when form is placed in the footer

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#952]
# Script Loading issue for onoffice-captchacontrol.min.js when form is placed in the footer

### User Story
As a website administrator, I want to ensure that all scripts required for the proper functioning of forms load correctly regardless of their placement within the website, so that users can interact with forms seamlessly, even when they are placed in the footer section of the site.

The website utilizes the onOffice for WP-Websites plugin that includes a script called onoffice-captchacontrol.min.js, which is responsible for handling reCAPTCHA functionality. This script is essential to ensure form submissions are protected from spam and automated submissions. The issue arises when a form created with the plugin is embedded in the footer of the website. While forms placed in the main body of the page function correctly, forms placed in the footer do not load the script as expected, resulting in errors.

### Current behavior
- When a form is placed outside of the footer section (e.g., in the main body of the page), the onoffice-captchacontrol.min.js script loads without issue.
- When the same form is placed within the footer section of the site the script onoffice-captchacontrol.min.js does not load correctly.
- Errors such as "onOffice is not a function" or "onOffice is not defined" are displayed in the browser's console.

This prevents the form from functioning properly, particularly regarding the reCAPTCHA verification.

### Steps to Reproduce:

1. Navigate to the plugin interface and create a new form. Ensure that reCAPTCHA is enabled both in the plugin settings and in the specific form configuration.
2. Place the generated shortcode for the form in the footer section of the website.
3. Load the webpage and inspect the console for JavaScript errors.
Note the presence of errors such as "onOffice is not a function" or "onOffice is not defined."

### Expected Behavior:
- The onoffice-captchacontrol.min.js script should load properly, regardless of whether the form is embedded in the main content or the footer.
- The reCAPTCHA functionality should work seamlessly, ensuring the form's usability and security.

**Comment by fredericalpers** [comment]
Update: For some of our clients the script is also not loaded on the property detail page inquiry form.

**Comment by dai-eastgate** [comment]
> Update: For some of our clients the script is also not loaded on the property detail page inquiry form.

I will check and fix it. Thanks!

**Comment by yeneastgate** [comment]
@fredericalpers If you want the file "onoffice-captchacontrol.min.js" to function properly when placing the form in the footer, it currently cannot be loaded as needed because it requires checking the shortcode in the page content. If you want it to load in the footer, we would have to revert to the previous method of loading all CSS and JS files.
Please let me know your thoughts on this issue.

**Comment by fredericalpers** [comment]
@yeneastgate Thank you for investigating this issue!

We'll need to discuss this internally to ensure we address it in the best way possible. I'll follow up with you once we've had a chance to review.

**Comment by yeneastgate** [comment]
> @yeneastgate Thank you for investigating this issue!
> 
> We'll need to discuss this internally to ensure we address it in the best way possible. I'll follow up with you once we've had a chance to review.

I got it, thanks!

**Comment by fredericalpers** [comment]
@yeneastgate I'm assuming this is the same problem for the property detailpage?

**Comment by yeneastgate** [comment]
> @yeneastgate I'm assuming this is the same problem for the property detailpage?

Yes. The bug (script onoffice-captchacontrol.min.js does not load properly.) will occur if we place the shortcode for the details in the footer section

**Comment by andernath** [comment]
@yeneastgate @dai-eastgate 

What about loading the scripts which are required for a form, when the template of the form is rendered?
I tried it on branch: https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/Bugfix/P%23121511-load-form-scripts-in-footer

It is not final and I still have Issues with captcha, but what do think? Any Pros or Cons?

**Comment by yeneastgate** [comment]
@andernath This appears to be an effective solution. Loading scripts when the form template is rendered seems like a reasonable approach to address the issue. This method eliminates the need to check shortcodes to load scripts.
Pros: Reduces unnecessary script loading and ensures that script dequeueing is done correctly.
Cons: So far, I've tested everything, and it all works well.
So, I will refactor the loading script based on your suggestion. Thanks.

**Comment by fredericalpers** [comment]
@yeneastgate please go ahead, thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thanks!

https://github.com/user-attachments/assets/21ab2fd7-da8a-416b-8df3-26c47dd395cf

**Comment by fredericalpers** [comment]
@dai-eastgate thank you! we will review this as soon as possible :)

**Comment by andernath** [comment]
> @fredericalpers Please take a look at my demo video and let me know your opinions. Thanks!
> 
>  recaptcha.load.in.footer.mp4

@dai-eastgate 
I have a problem while testing with reCaptcha Forms.
I don't know why but captchaControl.js is not loaded in header anymore, although the footer boolean is **false** while debugging. So I will get an error in browser consol: **onOffice.captchaControl is not a function** because the script is not ready...

Do you have any idea why this happen in my environment?
![image](https://github.com/user-attachments/assets/aa7ce4d9-5ad0-4ac1-aebd-cecb7a9ee2ce)

**Comment by dai-eastgate** [comment]
@andernath @fredericalpers 
I have restructured the code and tested it with the following results:
1. Tested on the Twenty Twenty-Four template: This template loads the plugin before the theme, so the script enqueueing is in the correct position, and everything works as expected. You can see this in the video.

https://github.com/user-attachments/assets/8c34ff88-6018-494f-92b7-28b931df3044

2. Tested on other templates: These themes load the entire head section before reaching the shortcode (plugin). Therefore, setting the footer boolean to false and then enqueueing the script doesn't work as intended because the head has already been loaded, and the script cannot be enqueued there anymore.

=> This issue is not feasible to resolve due to its dependency on the template. I suggest we either stick to the old method or continue with the current approach but ensure that scripts meant for the head are always loaded, rather than only when needed.
